# Generated by Django 5.0.3 on 2024-03-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customtoken_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customtoken",
            name="access_token",
            field=models.CharField(max_length=255),
        ),
    ]
